repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
- repo: local
  hooks:
    - id: mypy
      name: Install Poetry Dependencies and Run mypy
      entry: bash -c "poetry install --no-interaction --no-root --with tests && poetry run mypy pylspclient"
      language: system
- repo: local
  hooks:
    - id: poetry-pytest
      name: Run Tests with Poetry and Pytest
      entry: bash -c "poetry install --no-interaction --no-root --with tests && poetry run pytest"
      language: system
      types: [python]