name: Test Package
on:
  push:
    branches:
      - 'main'
  pull_request:
      branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install poetry
        uses: snok/install-poetry@v1.3.2

      - name: lint
        run: make lint

      - name: test
        run: make test
